name: Github Example Depolyment

on:
  push:
    branches:
      - main


jobs:
    install:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20]

        steps:
            - name: Checkout
            - uses: actions/checkout@v2

            - name: Using Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Run CI command
              run: npm ci

            - name: Check linting
              run: npm run lint
            
            - name: Run the tests
              run: npm run test

            - name: Build
              run: npm run build